# Generated by Django 3.0.3 on 2020-03-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
