# Generated by Django 3.0.3 on 2020-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20200309_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('abertura', models.FloatField()),
                ('fechamento', models.FloatField()),
                ('fechamento_ajustado', models.FloatField()),
                ('volume', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Acoes',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='BOVA11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='BOVA11.SA')),
                ('dados_historicos', models.ManyToManyField(to='contas.Acao')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
