# Generated by Django 3.0.3 on 2020-03-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20200323_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acao',
            new_name='HistoricalStock',
        ),
        migrations.RenameModel(
            old_name='BOVA11',
            new_name='Stock',
        ),
        migrations.AlterModelOptions(
            name='historicalstock',
            options={'ordering': ['data']},
        ),
    ]
